version: '2.1'

services: 
  reviewsite:
    build: 
      context: ./app
    
    ports: 
      - '9876:8000'
    volumes:
      - ./app:/app/src
    command: python3 reviewsite/manage.py runserver 0.0.0.0:8000